repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace

- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.9.0
  hooks:
    - id: commitizen
      stages: [commit-msg]